import SwiftUI

/// The admin's theme system, ported to Swift.
///
/// Values are transcribed verbatim from `packages/admin/src/theme-tokens.css`
/// (itself generated by `.audit/themes/gen-tokens.cjs`) — 4 themes × light/dark,
/// each WCAG AA verified there. Do NOT hand-tune these: fix the generator, then
/// re-transcribe, so web and mobile never drift into two different palettes.
///
/// SellRight has no locked Right Suite brand identity yet, so Vermillion is the
/// default here exactly as it is on the web.
enum ThemeName: String, CaseIterable, Identifiable {
    case vermillion, graphite, porcelain, carbon
    var id: String { rawValue }

    var label: String {
        switch self {
        case .vermillion: return "Vermillion"
        case .graphite: return "Graphite"
        case .porcelain: return "Porcelain"
        case .carbon: return "Carbon"
        }
    }
}

/// Light / Dark / System, mirroring the web switcher's three options.
enum ThemeMode: String, CaseIterable, Identifiable {
    case system, light, dark
    var id: String { rawValue }

    var label: String {
        switch self {
        case .system: return "System"
        case .light: return "Light"
        case .dark: return "Dark"
        }
    }

    var colorScheme: ColorScheme? {
        switch self {
        case .system: return nil
        case .light: return .light
        case .dark: return .dark
        }
    }
}

/// One theme's colors for one appearance.
struct ThemePalette {
    let bg: Color
    let surface: Color
    let surface2: Color
    let border: Color
    let borderStrong: Color
    let text: Color
    let textMuted: Color
    let textSubtle: Color
    let accent: Color
    let accentHover: Color
    let onAccent: Color
    let accentSoft: Color
    let success: Color
    let warning: Color
    let danger: Color
}

/// `rgb(203 61 20)` in the CSS → the same channel triple here. sRGB, matching
/// how the browser interprets the token.
private func c(_ r: Double, _ g: Double, _ b: Double) -> Color {
    Color(.sRGB, red: r / 255, green: g / 255, blue: b / 255, opacity: 1)
}

enum Theme {
    // MARK: - Palettes (transcribed from theme-tokens.css)

    static func palette(_ name: ThemeName, dark: Bool) -> ThemePalette {
        switch (name, dark) {
        case (.vermillion, false):
            return ThemePalette(
                bg: c(251, 248, 246), surface: c(255, 255, 255), surface2: c(244, 238, 234),
                border: c(233, 224, 217), borderStrong: c(214, 201, 191),
                text: c(31, 26, 23), textMuted: c(106, 95, 88), textSubtle: c(153, 139, 129),
                accent: c(203, 61, 20), accentHover: c(168, 46, 12), onAccent: c(255, 255, 255), accentSoft: c(252, 234, 227),
                success: c(21, 128, 61), warning: c(180, 83, 9), danger: c(180, 35, 24))
        case (.vermillion, true):
            return ThemePalette(
                bg: c(22, 17, 15), surface: c(30, 23, 20), surface2: c(38, 29, 25),
                border: c(52, 40, 35), borderStrong: c(70, 54, 46),
                text: c(244, 236, 231), textMuted: c(173, 157, 147), textSubtle: c(120, 106, 97),
                accent: c(255, 98, 66), accentHover: c(255, 124, 97), onAccent: c(22, 17, 15), accentSoft: c(51, 26, 18),
                success: c(74, 222, 128), warning: c(251, 191, 36), danger: c(248, 113, 113))

        case (.graphite, false):
            return ThemePalette(
                bg: c(247, 248, 250), surface: c(255, 255, 255), surface2: c(241, 243, 247),
                border: c(218, 222, 230), borderStrong: c(203, 209, 219),
                text: c(26, 29, 35), textMuted: c(91, 100, 114), textSubtle: c(138, 147, 163),
                accent: c(91, 91, 214), accentHover: c(74, 74, 196), onAccent: c(255, 255, 255), accentSoft: c(238, 238, 251),
                success: c(21, 128, 61), warning: c(180, 83, 9), danger: c(220, 38, 38))
        case (.graphite, true):
            return ThemePalette(
                bg: c(14, 15, 19), surface: c(22, 24, 29), surface2: c(29, 32, 38),
                border: c(40, 44, 52), borderStrong: c(54, 59, 69),
                text: c(236, 238, 242), textMuted: c(155, 163, 176), textSubtle: c(107, 114, 128),
                accent: c(124, 124, 240), accentHover: c(144, 144, 245), onAccent: c(14, 15, 19), accentSoft: c(30, 30, 58),
                success: c(74, 222, 128), warning: c(251, 191, 36), danger: c(248, 113, 113))

        case (.porcelain, false):
            return ThemePalette(
                bg: c(255, 255, 255), surface: c(255, 255, 255), surface2: c(245, 246, 248),
                border: c(230, 232, 236), borderStrong: c(201, 205, 212),
                text: c(10, 10, 10), textMuted: c(84, 89, 95), textSubtle: c(136, 142, 150),
                accent: c(11, 95, 255), accentHover: c(10, 79, 214), onAccent: c(255, 255, 255), accentSoft: c(232, 240, 255),
                success: c(4, 120, 87), warning: c(180, 83, 9), danger: c(220, 38, 38))
        case (.porcelain, true):
            return ThemePalette(
                bg: c(8, 9, 10), surface: c(15, 17, 18), surface2: c(23, 25, 27),
                border: c(35, 38, 41), borderStrong: c(52, 56, 60),
                text: c(250, 250, 250), textMuted: c(156, 163, 172), textSubtle: c(106, 112, 121),
                accent: c(77, 141, 255), accentHover: c(107, 160, 255), onAccent: c(8, 9, 10), accentSoft: c(17, 32, 58),
                success: c(52, 211, 153), warning: c(251, 191, 36), danger: c(248, 113, 113))

        case (.carbon, false):
            return ThemePalette(
                bg: c(247, 243, 236), surface: c(255, 253, 248), surface2: c(240, 234, 224),
                border: c(227, 218, 203), borderStrong: c(208, 195, 174),
                text: c(33, 28, 21), textMuted: c(107, 98, 83), textSubtle: c(148, 137, 122),
                accent: c(152, 92, 0), accentHover: c(126, 76, 0), onAccent: c(255, 255, 255), accentSoft: c(247, 236, 214),
                success: c(21, 128, 61), warning: c(180, 83, 9), danger: c(194, 65, 12))
        case (.carbon, true):
            return ThemePalette(
                bg: c(20, 17, 13), surface: c(28, 24, 19), surface2: c(36, 31, 24),
                border: c(50, 43, 34), borderStrong: c(68, 58, 44),
                text: c(242, 235, 223), textMuted: c(168, 156, 136), textSubtle: c(117, 107, 92),
                accent: c(245, 166, 35), accentHover: c(255, 185, 64), onAccent: c(20, 17, 13), accentSoft: c(42, 33, 20),
                success: c(107, 217, 104), warning: c(255, 201, 77), danger: c(255, 107, 92))
        }
    }

    /// Order/product state → color. Semantic tokens, not raw SwiftUI colors, so
    /// states re-theme with everything else.
    static func statusColor(_ state: String, _ p: ThemePalette) -> Color {
        switch state {
        case "Paid", "Delivered", "active": return p.success
        case "PaymentPending", "Draft", "draft": return p.warning
        case "Cancelled", "Refunded", "PartiallyRefunded": return p.danger
        case "Shipped": return p.accent
        default: return p.textMuted
        }
    }
}

/// Live theme selection. Persisted to UserDefaults, same as the web switcher
/// persists to localStorage.
@MainActor
@Observable
final class ThemeStore {
    var name: ThemeName {
        didSet { UserDefaults.standard.set(name.rawValue, forKey: "themeName") }
    }
    var mode: ThemeMode {
        didSet { UserDefaults.standard.set(mode.rawValue, forKey: "themeMode") }
    }

    init() {
        let storedName = UserDefaults.standard.string(forKey: "themeName") ?? ""
        let storedMode = UserDefaults.standard.string(forKey: "themeMode") ?? ""
        name = ThemeName(rawValue: storedName) ?? .vermillion
        mode = ThemeMode(rawValue: storedMode) ?? .system
    }

    /// Resolve against the environment's scheme when mode is .system.
    func palette(for scheme: ColorScheme) -> ThemePalette {
        let dark = mode == .system ? (scheme == .dark) : (mode == .dark)
        return Theme.palette(name, dark: dark)
    }
}

// MARK: - Environment plumbing

private struct PaletteKey: EnvironmentKey {
    static let defaultValue = Theme.palette(.vermillion, dark: false)
}

extension EnvironmentValues {
    /// The active palette. Read as `@Environment(\.palette) private var palette`.
    var palette: ThemePalette {
        get { self[PaletteKey.self] }
        set { self[PaletteKey.self] = newValue }
    }
}

/// Capsule badge for order/product state. Color + text; the web pairs these with
/// a status dot for colorblind safety, and the label here carries the same job.
struct StatusBadge: View {
    @Environment(\.palette) private var palette
    let text: String

    var body: some View {
        let color = Theme.statusColor(text, palette)
        Text(text)
            .font(.caption2.weight(.semibold))
            .padding(.horizontal, 8)
            .padding(.vertical, 3)
            .background(color.opacity(0.15), in: Capsule())
            .foregroundStyle(color)
    }
}
