/**
 * Invariant guard (ra-006): every hand-written migration in
 * packages/api/drizzle/ MUST keep its HAND-WRITTEN marker comment. If the
 * marker is missing, the file was likely silently rewritten by
 * `drizzle-kit generate`, which produces a migration that drifts from the
 * intended schema. The marker is the cheapest durable signal we can grep
 * for in CI without a snapshot diff.
 *
 * Run via `pnpm db:assert-hand-written`. Wired into `pnpm verify` so a
 * missing marker fails the same way as the FORCE-RLS guard.
 */
import { readFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
// this file lives at packages/api/src/db/; migrations live at packages/api/drizzle/
const MIGRATIONS_DIR = join(HERE, '..', '..', 'drizzle');

const HAND_WRITTEN = [
  '0032_cart_ttl.sql',
  '0034_subscriptions.sql',
  '0036_harden_subscription_rls.sql',
  '0037_payment_provider_ref_unique.sql',
  '0038_email_outbox.sql',
  '0039_push_notifications.sql',
];

const MARKER = '-- HAND-WRITTEN: see docs/runbooks/migrations.md';

async function main() {
  const offenders: string[] = [];
  for (const file of HAND_WRITTEN) {
    const path = join(MIGRATIONS_DIR, file);
    let body: string;
    try {
      body = await readFile(path, 'utf8');
    } catch (e) {
      offenders.push(`${file}: file missing at ${path} (was it deleted or moved?)`);
      continue;
    }
    if (!body.includes(MARKER)) {
      offenders.push(`${file}: HAND-WRITTEN marker missing — was this file regenerated by drizzle-kit? See docs/runbooks/migrations.md.`);
    }
  }
  if (offenders.length) {
    console.error('[assert-hand-written] FAIL — hand-written migrations drifted:');
    for (const o of offenders) console.error(`  - ${o}`);
    process.exit(1);
  }
  console.log(`[assert-hand-written] OK — ${HAND_WRITTEN.length} hand-written migrations carry the marker.`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
