/**
 * Invariant guard (ra-006): every hand-written migration in
 * packages/api/drizzle/ MUST keep its HAND-WRITTEN marker comment. If the
 * marker is missing, the file was likely silently rewritten by
 * `drizzle-kit generate`, which produces a migration that drifts from the
 * intended schema. The marker is the cheapest durable signal we can grep
 * for in CI without a snapshot diff.
 *
 * Run via `pnpm db:assert-hand-written`. Wired into `pnpm verify` so a
 * missing marker fails the same way as the FORCE-RLS guard.
 */
import { readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
// this file lives at packages/api/src/db/; migrations live at packages/api/drizzle/
// MIGRATIONS_DIR override: lets tests point the guard at a scratch fixture
// directory instead of the real drizzle/ folder (see assert-hand-written-
// migrations.test.ts), without touching real migration files.
const MIGRATIONS_DIR = process.env.MIGRATIONS_DIR ?? join(HERE, '..', '..', 'drizzle');

const HAND_WRITTEN = [
  '0032_cart_ttl.sql',
  '0034_subscriptions.sql',
  '0036_harden_subscription_rls.sql',
  '0037_payment_provider_ref_unique.sql',
  '0038_email_outbox.sql',
  '0039_push_notifications.sql',
  '0040_outbox_autovacuum.sql',
  '0041_subscriber.sql',
  '0042_payment_attempts.sql',
  '0043_cart_revision.sql',
  '0048_contact_submission.sql',
  '0049_restock_notify.sql',
  '0050_sheerid_verification.sql',
  '0051_dispute.sql',
  '0052_promotion_affiliate_email.sql',
  '0053_gateway_tenant_resolution.sql',
  '0055_payment_refund_identity.sql',
  '0057_email_change_outbox_dedupe.sql',
  '0058_cart_merged_status.sql',
  '0059_subscriber_signup_group.sql',
  '0060_gateway_tenant_resolution_strict.sql',
  '0061_passwordless_signin.sql',
  '0064_licensing_engine.sql',
  '0066_storekit.sql',
  '0068_seo_surface.sql',
  '0069_resolver_role_ownership.sql',
];

const MARKER = '-- HAND-WRITTEN: see docs/runbooks/migrations.md';

// Escape hatch for migrations that were applied to a real database BEFORE the
// exact MARKER text existed (or before it was added to that file). Such a file
// must never be edited again — including to retrofit the marker — because its
// bytes are already applied; pin it by content hash instead. Empty by default:
// populate a `{ filename: sha256hex }` entry only for a migration that truly
// predates the marker convention and has already shipped.
const LEGACY_SHA256: Record<string, string> = {};

async function main() {
  const offenders: string[] = [];
  for (const file of HAND_WRITTEN) {
    const path = join(MIGRATIONS_DIR, file);
    let bytes: Buffer;
    try {
      bytes = await readFile(path);
    } catch (e) {
      offenders.push(`${file}: file missing at ${path} (was it deleted or moved?)`);
      continue;
    }
    const legacyHash = LEGACY_SHA256[file];
    if (legacyHash) {
      if (createHash('sha256').update(bytes).digest('hex') !== legacyHash) {
        offenders.push(`${file}: legacy byte hash mismatch; preserve applied SQL and add a new migration.`);
      }
    } else if (!bytes.toString('utf8').includes(MARKER)) {
      offenders.push(`${file}: HAND-WRITTEN marker missing — was this file regenerated by drizzle-kit? See docs/runbooks/migrations.md.`);
    }
  }
  if (offenders.length) {
    console.error('[assert-hand-written] FAIL — hand-written migrations drifted:');
    for (const o of offenders) console.error(`  - ${o}`);
    process.exit(1);
  }
  const legacyCount = Object.keys(LEGACY_SHA256).length;
  console.log(`[assert-hand-written] OK — ${HAND_WRITTEN.length} hand-written migrations verified${legacyCount ? ` (${legacyCount} legacy byte hashes; remaining files marked)` : ' (marker check)'}.`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
