#!/usr/bin/env bash
# One-time: create the NON-owner application DB role `sellright_app` (research §1,
# AWS-canonical RLS pattern) and write a 0600 env file with both connection URLs.
# The API runs as sellright_app (fail-closed under FORCE RLS); migrations / seed /
# jobs run as the owner. Must be run while connected as the OWNER role.
#
# Usage: APP_DB_PASSWORD=<pw> bash create-app-role.sh
set -euo pipefail
APP_PW="${APP_DB_PASSWORD:?set APP_DB_PASSWORD env}"
export PNPM_HOME="$HOME/.local/share/pnpm"; export PATH="$PNPM_HOME:$PATH"

# Owner DATABASE_URL — inherited from the currently-running API (still owner now).
APIPID="$(pgrep -f 'src/index.ts' | head -1)"
set -a; eval "$(tr '\0' '\n' < /proc/$APIPID/environ | grep -E '^DATABASE_URL=' | sed 's/^/export /')"; set +a
OWNER_URL="$DATABASE_URL"

WHO="$(psql "$OWNER_URL" -tAc 'select current_user')"
if [ "$WHO" = "sellright_app" ]; then echo "FATAL: connected as sellright_app; need the owner role" >&2; exit 1; fi
echo "[create-app-role] connected as owner: $WHO"

psql "$OWNER_URL" -v ON_ERROR_STOP=1 -v pw="$APP_PW" <<'SQL'
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='sellright_app') THEN
    EXECUTE format('ALTER ROLE sellright_app LOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE PASSWORD %L', :'pw');
  ELSE
    EXECUTE format('CREATE ROLE sellright_app LOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE PASSWORD %L', :'pw');
  END IF;
END $$;
GRANT USAGE ON SCHEMA public TO sellright_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO sellright_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sellright_app;
-- registries are read-only to the app (writes happen via the owner: seed-admin/migrations)
REVOKE INSERT, UPDATE, DELETE ON "store", "admin_user", "admin_user_store" FROM sellright_app;
-- future owner-created tables auto-grant DML to the app role
ALTER DEFAULT PRIVILEGES FOR ROLE sellright IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO sellright_app;
ALTER DEFAULT PRIVILEGES FOR ROLE sellright IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO sellright_app;
SQL
echo "[create-app-role] role + grants applied"

# Grant CONNECT on the actual database (name parsed from the URL).
DBNAME="${OWNER_URL##*/}"; DBNAME="${DBNAME%%\?*}"
psql "$OWNER_URL" -v ON_ERROR_STOP=1 -c "GRANT CONNECT ON DATABASE \"$DBNAME\" TO sellright_app;"

# Build the app URL by swapping creds; keep host:port/db from the owner URL.
HOSTDB="${OWNER_URL#*@}"            # 127.0.0.1:5433/sellright_dev
APP_URL="postgres://sellright_app:${APP_PW}@${HOSTDB}"

mkdir -p "$HOME/.sellright"
umask 177
cat > "$HOME/.sellright/env" <<EOF
# SellRight DB connection URLs (0600). App = non-owner (RLS fail-closed);
# OWNER = migrations/seed/jobs. Generated by create-app-role.sh.
DATABASE_URL_APP=${APP_URL}
DATABASE_URL_OWNER=${OWNER_URL}
EOF
chmod 600 "$HOME/.sellright/env"
echo "[create-app-role] wrote ~/.sellright/env (0600)"

# Prove the app role works AND is fail-closed: connect as app, no store context.
echo "[create-app-role] app-role probe (no store context -> data tables must be empty/denied):"
psql "$APP_URL" -tAc "select 'whoami='||current_user;"
psql "$APP_URL" -tAc "select 'stores_visible='||count(*) from store;"            # registry -> visible
psql "$APP_URL" -tAc "select 'admin_acl_visible='||count(*) from admin_user_store;" # registry -> visible
psql "$APP_URL" -tAc "select 'orders_without_context='||count(*) from \"order\";"    # FORCE RLS -> 0
echo "[create-app-role] done"
